version: "3.9"
services:
  nowgotrip:
    container_name: nowgotrip
    image: registry.cn-hangzhou.aliyuncs.com/glhub/nowgotrip
    ports:
      - 4000:3000
    environment:
      - DUCK_DUCK_GO_BASE_URL= http://host.docker.internal:8304
      - HTTP_PROXY=http://host.docker.internal:7897
      - HTTPS_PROXY=http://host.docker.internal:7897
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - duckduckgo-api
  duckduckgo-api:
    image: duckduckgo-api
    container_name: duckduckgo
    restart: always
    ports:
      - "8304:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
